"""
vuln_report_writer.py — Saves a structured Markdown vulnerability report.

Output: reports/vuln_report_<timestamp>.md

The Markdown file is structured so it can be imported into external tools
(Word, Dradis, Pentest.WS) or extended for follow-up reports.
"""

import os
import datetime
from typing import List

# ──────────────────────────────────────────────────────────────────────────────
#  CVSS severity → emoji badge
# ──────────────────────────────────────────────────────────────────────────────

_SEV_BADGE = {
    "CRITICAL": "🔴 CRITICAL",
    "HIGH":     "🟠 HIGH",
    "MEDIUM":   "🟡 MEDIUM",
    "LOW":      "🟢 LOW",
    "NONE":     "⚪ NONE",
}

_TIER_BADGE = {
    "LOW":    "🔴 LOW  (Insecure)",
    "MEDIUM": "🟡 MEDIUM (Moderate Risk)",
    "HIGH":   "🟢 HIGH (Secure)",
}


# ──────────────────────────────────────────────────────────────────────────────
#  Public entry point
# ──────────────────────────────────────────────────────────────────────────────

def save_vuln_markdown(findings, tier: str, card: dict, profile: dict) -> str:
    """
    Write a Markdown vulnerability report and return the saved file path.

    Parameters
    ----------
    findings : list[VulnFinding]  — from vuln_engine.generate_vuln_report()
    tier     : str                — "LOW" | "MEDIUM" | "HIGH"
    card     : dict               — card identification dict from main.py
    profile  : dict               — card profile from CARD_DATABASE
    """
    timestamp   = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename    = f"vuln_report_{timestamp}.md"
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    reports_dir  = os.path.join(project_root, "reports")
    os.makedirs(reports_dir, exist_ok=True)
    filepath = os.path.join(reports_dir, filename)

    lines = _build_markdown(findings, tier, card, profile, timestamp)

    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        return filepath
    except Exception as e:
        return f"[ERROR: {e}]"


# ──────────────────────────────────────────────────────────────────────────────
#  Markdown builder
# ──────────────────────────────────────────────────────────────────────────────

def _build_markdown(findings, tier, card, profile, timestamp) -> list:
    scan_dt  = datetime.datetime.strptime(timestamp, "%Y%m%d_%H%M%S")
    scan_str = scan_dt.strftime("%Y-%m-%d %H:%M:%S")
    family   = card.get("family", profile.get("family", "Unknown"))
    standard = profile.get("standard", "Unknown")
    freq     = profile.get("freq", "Unknown")
    crypto   = profile.get("crypto", "None")
    tier_str = _TIER_BADGE.get(tier, tier)

    md = []

    # ── Title ─────────────────────────────────────────────────────────────────
    md += [
        "# RFID/NFC Security Vulnerability Report",
        "",
        f"> **Generated by:** Proxmark3 RFID Security Analyzer  ",
        f"> **Scan Date:** {scan_str}  ",
        f"> **Card Type:** {family}  ",
        f"> **Security Tier:** {tier_str}  ",
        "",
        "---",
        "",
    ]

    # ── Executive Summary ─────────────────────────────────────────────────────
    md += [
        "## Executive Summary",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| Card Family | {family} |",
        f"| Frequency | {freq} |",
        f"| Standard | {standard} |",
        f"| Cryptography | {crypto or 'None'} |",
        f"| Total Findings | {len(findings)} |",
        f"| Security Tier | **{tier_str}** |",
        "",
    ]

    # Tier summary paragraph
    tier_msgs = {
        "LOW": (
            "⚠️ **This card presents a CRITICAL/HIGH risk profile.** "
            "One or more vulnerabilities with a CVSS score ≥ 7.0 were identified. "
            "Exploitation requires minimal skill and commodity hardware. "
            "Immediate remediation is strongly recommended."
        ),
        "MEDIUM": (
            "⚠️ **This card presents a MODERATE risk profile.** "
            "Vulnerabilities exist that could be exploited under specific conditions. "
            "Remediation should be planned and prioritized."
        ),
        "HIGH": (
            "✅ **This card presents a LOW / acceptable risk profile.** "
            "No high-severity vulnerabilities were identified. "
            "Continue to apply best-practice key management and monitoring."
        ),
    }
    md += [tier_msgs.get(tier, ""), "", "---", ""]

    if not findings:
        md += [
            "## Vulnerability Findings",
            "",
            "_No significant vulnerabilities identified for this card type._",
            "",
            "---",
            "",
        ]
    else:
        # ── CVSS Summary Table ─────────────────────────────────────────────────
        md += [
            "## Vulnerability Summary Table",
            "",
            "| ID | Title | CVSS Score | Severity |",
            "|---|---|---|---|",
        ]
        for f in findings:
            badge = _SEV_BADGE.get(f.cvss_severity, f.cvss_severity)
            md.append(f"| {f.vuln_id} | {f.title} | {f.cvss_score:.1f} | {badge} |")

        md += ["", "---", ""]

        # ── Per-Finding Detail Sections ────────────────────────────────────────
        md += ["## Detailed Vulnerability Findings", ""]

        for finding in findings:
            badge = _SEV_BADGE.get(finding.cvss_severity, finding.cvss_severity)
            md += [
                f"### {finding.vuln_id} — {finding.title}",
                "",
                f"**Severity:** {badge}  ",
                f"**CVSS v3.1 Score:** `{finding.cvss_score:.1f} / 10.0`  ",
                f"**CVSS Vector:** `{finding.cvss_vector}`  ",
                "",
                "#### Description",
                "",
                finding.description,
                "",
                "#### Exploit Scenario",
                "",
                "```",
                finding.exploit_scenario,
                "```",
                "",
                "#### Remediation",
                "",
                f"> {finding.remediation}",
                "",
                "---",
                "",
            ]

    # ── Remediation Summary Table ──────────────────────────────────────────────
    if findings:
        md += [
            "## Remediation Priority Table",
            "",
            "| Priority | ID | Action |",
            "|---|---|---|",
        ]
        for i, f in enumerate(findings, 1):
            short_rem = f.remediation.split(".")[0].strip()
            md.append(f"| {i} | {f.vuln_id} | {short_rem} |")
        md += ["", "---", ""]

    # ── Crypto Analysis Note ──────────────────────────────────────────────────
    md += [
        "## Cryptographic Posture",
        "",
    ]

    crypto_str = str(profile.get("crypto", "")).upper()
    broken     = profile.get("broken_crypto", False)

    if not profile.get("crypto"):
        md += [
            "| Property | Status |",
            "|---|---|",
            "| Algorithm | ❌ None |",
            "| Confidentiality | ❌ None — plaintext RF |",
            "| Integrity | ❌ None |",
            "| Authentication | ❌ None |",
            "",
            "> **Risk:** All data is transmitted in plaintext. No cryptographic "
            "protection exists at any layer.",
        ]
    elif broken:
        alg = profile.get("crypto", "Unknown")
        md += [
            "| Property | Status |",
            "|---|---|",
            f"| Algorithm | ⚠️ {alg} (BROKEN) |",
            "| Confidentiality | ⚠️ Weak — cipher is publicly reversible |",
            "| Integrity | ⚠️ Weak |",
            "| Authentication | ⚠️ One-sided and reversible |",
            "",
            f"> **Risk:** The `{alg}` cipher has been publicly broken. "
            "Key material can be recovered using open-source Proxmark3 tools.",
        ]
    elif "AES" in crypto_str or "RSA" in crypto_str:
        note = ""
        if "AES" in crypto_str:
            note = (
                "**AES-128** is a symmetric block cipher standardised by NIST (FIPS 197). "
                "With mutual authentication and fresh session keys, AES-128 provides "
                "128 bits of symmetric security — computationally infeasible to break "
                "with current or near-future hardware."
            )
        if "RSA" in crypto_str:
            note += (
                " **RSA** (asymmetric) is used for key exchange / certificate verification "
                "in EMV cards. RSA-2048 provides ~112 bits of security, suitable for "
                "transaction authentication lifetimes. Combined with per-transaction ARQC "
                "cryptograms, replay and forgery attacks are blocked."
            )
        md += [
            "| Property | Status |",
            "|---|---|",
            f"| Algorithm | ✅ {profile.get('crypto')} |",
            "| Confidentiality | ✅ Strong |",
            "| Integrity | ✅ MAC / cryptogram protected |",
            "| Authentication | ✅ Mutual (challenge-response) |",
            "",
            f"> {note}",
        ]
    else:
        md += [
            f"| Algorithm | {profile.get('crypto', 'Unknown')} |",
            "",
        ]

    md += ["", "---", ""]

    # ── CVSS Methodology Note ─────────────────────────────────────────────────
    md += [
        "## Appendix — CVSS v3.1 Scoring Methodology",
        "",
        "Vulnerability scores in this report use the "
        "[CVSS v3.1 specification](https://www.first.org/cvss/v3.1/specification-document) "
        "from FIRST.org. The following metrics were considered:",
        "",
        "| Metric | Consideration |",
        "|---|---|",
        "| Attack Vector (AV) | Physical (P) for on-card attacks; Adjacent (A) for RF range; Network (N) for relay |",
        "| Attack Complexity (AC) | Low (L) for trivial attacks; High (H) for complex timing/equipment requirements |",
        "| Privileges Required (PR) | None (N) — no prior access needed for passive attacks |",
        "| User Interaction (UI) | None (N) — card holder unaware |",
        "| Scope (S) | Unchanged (U) for single system; Changed (C) if entire infrastructure affected |",
        "| Confidentiality (C) | High (H) if credentials / PAN exposed |",
        "| Integrity (I) | High (H) if card can be cloned/modified |",
        "| Availability (A) | Low (L) / None (N) for most RF attacks |",
        "",
        "> Scores reflect the **Base Score** only. "
        "Temporal and Environmental metrics may modify scores in your specific deployment.",
        "",
        "---",
        "",
        f"*Report generated by Proxmark3 RFID Security Analyzer — {scan_str}*",
    ]

    return md
